var CatherinePeyretone = {
    name: "Catherine Peyretone",
    description: "12 years ago, Catherine Peyretone met the devil in the shape of a rabbit in France. He ate the flesh of children and even destroyed the fruit and crops of Montpellier.",
    specialAbility: "destroy fruit and crops",
    health: 100,
    attack: 20,
    stamina: 100,
    strength: 100,
    torture: 100,
    intelligence: 100,
    wisdom: 100,
    charisma: 100,
    luck: 100,
    magicResistance: 100,
}